<?php
/**
 * Load data from admin panel for use in website
 * This file loads menu, translations, and settings from admin panel
 */

$adminDataDir = __DIR__ . '/admin/data';

function loadAdminData($file) {
    global $adminDataDir;
    $path = $adminDataDir . '/' . $file;
    if (file_exists($path)) {
        $content = file_get_contents($path);
        return json_decode($content, true);
    }
    return null;
}

// Load data
$menu = loadAdminData('menu.json');
$translations = loadAdminData('translations.json');
$settings = loadAdminData('settings.json');

// Output as JavaScript
header('Content-Type: application/javascript');
?>
// Auto-generated from admin panel
// Do not edit this file manually

window.AdminData = {
    menu: <?php echo json_encode($menu, JSON_UNESCAPED_UNICODE); ?>,
    translations: <?php echo json_encode($translations, JSON_UNESCAPED_UNICODE); ?>,
    settings: <?php echo json_encode($settings, JSON_UNESCAPED_UNICODE); ?>
};

